// Workspace.swift
import ProjectDescription

let workspace = Workspace(
    name: "Example",
    projects: [
        "Projects/Example/**"
    ],
    //schemes: <#T##[Scheme]#>,
    //fileHeaderTemplate: <#T##FileHeaderTemplate?#>,
    //additionalFiles: <#T##[FileElement]#>,
    generationOptions: .options(
        //enableAutomaticXcodeSchemes: <#T##Bool?#>,
        autogeneratedWorkspaceSchemes: .disabled
        //lastXcodeUpgradeCheck: <#T##Version?#>,
        //renderMarkdownReadme: <#T##Bool#>
    )
)

